### ISSUE TITLE
Don't have any functionality to change the default error messages

### ISSUE THREAD

**Issue by maikeldaloo** [sha256/Pristine#1]
Hey there,

Nice library you have here, but I'm just wondering if there's any plan on adding the ability to customise the error message text for the default validations, e.g. `required` gives the error "This field is required".

Seems that I have to do a silent validation add my own errors.

On a side note, on your Demos page, only 1 demo works, the rest are blank HTML files.

**Comment by maikeldaloo** [comment]
Second time I'm using your plugin in a project and again, I really find myself needing to be able to customise the error messages.

**Comment by sha256** [comment]
@maikeldaloo, looks like there's already a way to add custom error messages, but I forgot to add it in the documentation and also forgot that I actually wrote this feature!

Just add an attribute on the input field like this:
`data-pristine-required-message="My custom message"`

[Demo here](https://codepen.io/sha256/pen/JezmLp)

Cheers!

**Comment by maikeldaloo** [comment]
Oh man, I'm very happy to hear that!
Good work. I just tested it and it works just as expected 👍.

@sha256 Do you want to keep this issue open until you update the docs?

**Comment by sha256** [comment]
@maikeldaloo thanks man! Updated the docs, so closing this issue.
