### ISSUE TITLE
RegEx in pattern containing commas breaks validation

### ISSUE THREAD

**Issue by missmatsuko** [sha256/Pristine#11]
Example: https://jsfiddle.net/n9jcwukp/

This error shows in the console when you type in the 2nd input which has a comma in the pattern:
```
Uncaught TypeError: Cannot read property '1' of null
```

It may have something to do with [this line](https://github.com/sha256/Pristine/blob/b54e1bf1e97dbeb39e0933cfd1b4d2cde620d352/src/pristine.js#L91), which splits all parameters at commas.

**Comment by besimhu** [comment]
@missmatsuko did you have a workaround this specific regex pattern

**Comment by missmatsuko** [comment]
I think if you remove the starting/ending delimiters, it will work like a
minimum count match. But that might not work for you, depending on your
use-case/what the rest of your regex is like.

**Comment by missmatsuko** [comment]
Oh there's also the `+` symbol which is the same as `{1,}`. If `+` works,
it could be used for a minimum 1 count match. Maybe there's a hacky way to
make it work for a higher minimum count.

**Comment by luca-vercelli** [comment]
This is very bad. One would like to say `pattern="/.{8,}/" `to say "_password must be at least 8 characters length_".

@missmatsuko you are right, the problem is in line https://github.com/sha256/Pristine/blob/b54e1bf1e97dbeb39e0933cfd1b4d2cde620d352/src/pristine.js#L91

Pristine here thinks that we are giving two arguments, `"/.{8"` and `"}/"`.

**Comment by luca-vercelli** [comment]
@sha256  I suggest that a validator should have one attribute more, say `param_separator`. By default its value is `","`, and for the pattern validator its value is `null`. The parameters should be splitted according to that value.

I already checked that `"aa,bb,cc".split(null)` is accepted and returns `["aa,bb,cc"]` .

**Comment by missmatsuko** [comment]
I think the solution is to not split parameters by comma, at least not for `pattern`.

**Comment by sha256** [comment]
Yeah, separating by comma seemed natural but it's definitely a wrong choice. `param-separator` sounds like a good option. I can think of one issue though: an input can have multiple validators including built-in and custom ones, what if 2 validators need 2 different separator?  `data-pristine-pattern-param-separator`?

**Comment by missmatsuko** [comment]
You can make a regex that matches both patterns you have in mind and use that as the value for pattern.

**Comment by luca-vercelli** [comment]
> 
> 
> Yeah, separating by comma seemed natural but it's definitely a wrong choice. `param-separator` sounds like a good option. I can think of one issue though: an input can have multiple validators including built-in and custom ones, what if 2 validators need 2 different separator? `data-pristine-pattern-param-separator`?

Indeed each validator should have its own separator, something like:

```
const _ = function (name, validator) {
    validator.name = name;
    if (!validator.msg)
        validator.msg = lang[name];
    if (validator.priority === undefined)
        validator.priority = 1;
    if (validator.separator_name === undefined)
        validator.separator_name = ',';
    validators[name] = validator;
};
```

**Comment by luca-vercelli** [comment]
And, probably, one have to modify the `self.addValidator()` function too.

**Comment by sha256** [comment]
I agree with @missmatsuko, adding separator does not seem like a cleaner approach. We can just avoid splitting for `pattern` and document it.  

I did not understand this part though:

> You can make a regex that matches both patterns you have in mind and use that as the value for pattern.
> 
> The OR operator might be useful:
> http://www.rexegg.com/regex-quickstart.html#logic

Could you explain a little bit?

**Comment by missmatsuko** [comment]
I just meant if you did want to match multiple patterns you could make a single regex for it, and using the or operator could be helpful for that.

**Comment by sha256** [comment]
> I just meant if you did want to match multiple patterns you could make a single regex for it, and using the or operator could be helpful for that. 

Yeah, makes sense.
