### ISSUE TITLE
Issue faced with adding a global validator

### ISSUE THREAD

**Issue by xavianaxw** [sha256/Pristine#3]
Codepen
https://codepen.io/xavianaxw/pen/EGeWLj

Description
I've tried setting up PristineJS with a custom global validator `my-range` that throws an error when the value input is not between the minimum and maximum value. This was as per the example on the README.

In my HTML, I've set the input to respect the `required` and `data-pristin-my-range="10,30"` rule.

Expected behavior
1. Input throws an error on `required`
2. Input throws an error on `data-pristine-my-range` if not between 10 - 30

Outcome
1. Input does throw an error on `required`
2. Input does not respect `data-pristine-my-range` rule set.

Would be best if you can help point me in the right direction!

Cheers

**Comment by sha256** [comment]
Hi @xavianaxw, this issue has been fixed. Please check https://codepen.io/sha256/pen/ZPOoYp

**Comment by xavianaxw** [comment]
Cool
