### ISSUE TITLE
how to update pristine when attributes change dynamically

### ISSUE THREAD

**Issue by badpenguin** [sha256/Pristine#39]
When adding or removing the required attribute it seems that pristine does not detect the change.
Wich is the correct way to tell pristine that the dom has changed?

**Comment by sha256** [comment]
Pristine does not observe attribute changes. So when you need to change attributes you have to re-initialize the pristine object like this:

```
pristine.reset(); // resets errors
pristine.destroy(); // clean up
pristine = new Pristine(form); // re-init
```

**Comment by badpenguin** [comment]
Solved
