### ISSUE TITLE
Add error after ajax submissions

### ISSUE THREAD

**Issue by thewebartisan7** [sha256/Pristine#46]
After form validation passed, I am making an ajax form submission, and then catch errors from server which make additional validation.

I have used before with custom JS to append errors but this are not removed by pristine, so I see method addError and this correctly mark input invalid, but don't show error message.

Am I missing something? Should addError also append error message?

This is my code:

```js
  axios({
            method: method,
            url: url,
            data: data
        })
            .then(function (response) {
               // success here removed
            })
            .catch(function (error) {

                   // Part of code that matters here
                        let errors = error.response.data.errors
                        for (let input in errors) {
                            if (errors.hasOwnProperty(input)) {
                                // Avoid to show message if already exist
                                if (!form.querySelector('.invalid-feedback-' + input)) {

                                    // Add error using pristine
                                    pristine.addError(form.querySelector('[name="'+input+'"]'), errors[input][0])

                                    // I used below code to append invalid feedback:

                                    // let invalidFeedback = document.createElement("div");
                                    // invalidFeedback.classList.add('invalid-feedback', 'invalid-feedback-' + input)
                                    // invalidFeedback.style.display = 'block'
                                    // invalidFeedback.innerHTML = errors[input][0]
                                    // let inputElement = form.querySelector('[name="'+input+'"]')
                                    // inputElement.classList.add('is-invalid')
                                    // if(inputElement) {
                                    //     inputElement.parentNode.insertBefore(invalidFeedback, inputElement.nextSibling)
                                    // }
                                }
                            }
                        }
            })
```

Thanks

**Comment by sha256** [comment]
Does it show error messages if there's error before the ajax submission?
If it can correctly mark the input as invalid and cannot show the error message, there's probably an issue with `errorTextParent` config.

**Comment by thewebartisan7** [comment]
I found issue, my fault.

I didn't remove my code that remove invalid-feedback on form submit, so this code somehow conflict with pristine.

I have immediately before ajax submit:

         [].slice.call(document.querySelectorAll('.invalid-feedback')).map(function (invalidFeedback) {
             invalidFeedback.remove()
         });
 
         [].slice.call(document.querySelectorAll('input.is-invalid')).map(function (invalidInput) {
             invalidInput.classList.remove('is-invalid')
         })
