### ISSUE TITLE
Functionnality to use var into a addValidator for the error message

### ISSUE THREAD

**Issue by Dayniight** [sha256/Pristine#8]
Hi Sha,

First, thanks for your library, it's pretty cool and easy to use.

I'm currently looking to add custom message error into an "addValidator", but when i try to use it, i cant get my var out of the scope (pwdError).

    var password = form.querySelector('.passwordValidate');
    var regEx = {
        char : new RegExp("^(?=.{8,})"),
        maj : new RegExp("^(?=.*[A-Z])"),
        min : new RegExp("^(?=.*[a-z])"),
        num : new RegExp("^(?=.*[0-9])"),
        spe : new RegExp("^(?=.*[!@#\$%\^&\*])")
    }
    var pwdText = {
        char : '8 caractères',
        maj : '1 majuscule',
        min : '1 minuscule',
        num : '1 chiffre',
        spe : 'un caractère spécial'        
    }

    if(password) {
        let pwdError = '';
        let regex = function (password) {

            pwdError = '';
            Object.keys(regEx).forEach((key) => {
                if(!regEx[key].test(password.value) && pwdError.replace((pwdText[key]), '') === pwdError ) {
                    pwdError = pwdError + ', ' + pwdText[key];
                }
                else {
                    return true;
                }
            })

            if(pwdError == '') {
                pwdError = '';
            }
            else {
                pwdError = 'Votre mot de passe doit contenir au minimum' + pwdError + '.';
            }
            console.log(pwdError)
            return false;
        }
        pristine.addValidator(password, function() {
            regex(password);
        }, 'pwdError', 2, true);
    }

pwdError is null but the console.log is full.

**Comment by sha256** [comment]
Hi @Dayniight, could you post this in codepen.io and share the link? I think I can come up with a solution.

**Comment by Dayniight** [comment]
Hi @sha256,

This is my solution for it : 

Now i return an array with a boolean and the error message like this : 

```
var password = form.querySelector('.passwordValidate');
var regEx = {
    char : new RegExp("^(?=.{8,})"),
    maj : new RegExp("^(?=.*[A-Z])"),
    min : new RegExp("^(?=.*[a-z])"),
    num : new RegExp("^(?=.*[0-9])"),
    spe : new RegExp("^(?=.*[!@#\$%\^&\*])")
}
var pwdText = {
    char : '8 caractères',
    maj : '1 majuscule',
    min : '1 minuscule',
    num : '1 chiffre',
    spe : 'un caractère spécial'        
}

let pwdError = '';

pristine.addValidator(password, function() {

    pwdError = '';
    Object.keys(regEx).forEach((key) => {
        if(!regEx[key].test(password.value) && pwdError.replace((pwdText[key]), '') === pwdError ) {
            pwdError = pwdError + ', ' + pwdText[key];
        }
    })

    if(!pwdError == '') {
        pwdError = 'Votre mot de passe doit contenir au minimum' + pwdError + '.';
    }
    else {
        return [true, ''];
    }

    return [false, pwdError];
}, '', 2, true);
```



And i process into your code like that : 

```
    function _validateField(field) {
        var errors = [];
        var valid = true;
        for (var i in field.validators) {
            var validator = field.validators[i];
            var params = field.params[validator.name] ? field.params[validator.name] : [];
            params[0] = field.input.value;
            if (!validator.fn.apply(field.input, params)[0]) {
                valid = false;
                var error = field.messages[validator.name] || validator.fn.apply(field.input, params)[1] || validator.msg;
                console.log(validator.msg)
                errors.push(tmpl.apply(error, params));
                if (validator.halt === true) {
                    break;
                }
            }
        }
        field.errors = errors;
        return valid;
    }
```

With this process i can easly return a var with a custom message edited into the addValidator

**Comment by sha256** [comment]
@Dayniight, I get what you're doing but I still think adding multiple validator in a loop is a cleaner solution because of the dependency on template syntaxes in the message string and also it does not require modifying the library. Anyway, 

`var params = field.params[validator.name] ? field.params[validator.name] : [];
            params[0] = field.input.value;
            if (!validator.fn.apply(field.input, params)[0]) {
                valid = false;
                var error = field.messages[validator.name] || validator.fn.apply(field.input, params)[1] || validator.msg;
                console.log(validator.msg)
                errors.push(tmpl.apply(error, params));
                if (validator.halt === true) {
                    break;
                }
            }`

This could be improved by
`var params = field.params[validator.name] ? field.params[validator.name] : [];
            params[0] = field.input.value;
            var result = validator.fn.apply(field.input, params);
            if (!result[0]) {
                valid = false;
                var error = field.messages[validator.name] || result[1] || validator.msg;
                errors.push(tmpl.apply(error, params));
                if (validator.halt === true) {
                    break;
                }
            }`
